### PR TITLE
Update information on home page and fix minor issues

### LINKED ISSUE #118: Improve site information
Improve information on the site, ensuring it is professional and provides sufficient clarity.

- How it works
- FAQ

### PR DESCRIPTION
**Pull request by habbes**
## Related Issues

*List of issues fixed by this pull request*

Fixes #118 #122 

## Description

- [x] Improve text and information on home page
- [x] Display amount distributed on home page stats
- [x] Fix computation of amount contributed to deduct amount refunded
- [x] Add testimonials
- [x] Add FAQ

Other issues:
- [x] Only display beneficiary's first name (instead of full name) in donation notification message sent to donor.
- [x] User actual name instead of email address on the name field of ManualPay transactions

### CODE REVIEW

File: webapp/src/views/home/home.vue [hunk 1]
```diff
@@ -16,72 +16,91 @@
...
-      <section class="my-5 pt-5 text-center" id="beneficiaries">
-        <h1 class="text-primary mb-5">The Beneficiaries</h1>
+      <section class="my-5 pt-5 text-center" id="how-it-works">
         <p>
-          All beneficiaries get <span class="text-secondary font-weight-bold">Ksh 2,000</span> 
-          to get basic supplies during this trying period. <br/>
-          Here are some of the people whom your contribution will go along to help.
+          Social Relief aims to send <span class="text-secondary font-weight-bold">Ksh 2,000</span> 
+          per month to each beneficiary on the platform between September and November 2020.<br/>
+          This amount will help those in need address their basic needs and get back on their feet following
```
Comment (BambanzaJuniorThe2nd) [inline webapp/src/views/home/home.vue:43]: Put a `to` between `need` and `address`, as in `This amount will help those in need to address...`

File: webapp/src/data/faqs.ts [hunk 2]
```diff
@@ -0,0 +1,45 @@
...
+  {
+    question: 'Who runs SocialRelief?',
+    answer: 'test'
+  },
+  {
+    question: 'Who are the beneficiaries and how are they enrolled to the program?',
+    answer: 'test'
+  },
+  {
+    question: 'How are donations sent to beneficiaries',
```
Comment (BambanzaJuniorThe2nd) [inline webapp/src/data/faqs.ts:17]: Put a question mark

File: webapp/src/data/faqs.ts [hunk 3]
```diff
@@ -0,0 +1,45 @@
...
+    answer: 'We have an automated distribution process that runs every day.' +
+      ' This process finds all eligible beneficiaries and allocates available funds for each of them, potentially from different donors.' +
+      ' It then transfers the funds directly to beneficiaries via M-Pesa transfer.' +
+      ' The process ensures that no beneficiary receives more than 2,000Ksh within a 30-day period.' +
+      ' It is possible for some beneficiaries not to reach the target 2,000Ksh per month or not to receive any funds at all if there is not enough money to go around'
+  },
+  {
+    question: 'When will I know whether my donation has been used',
```
Comment (BambanzaJuniorThe2nd) [inline webapp/src/data/faqs.ts:25]: Same comment as above

**Review by BambanzaJuniorThe2nd — APPROVED** [review]
